### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by vosykapavel** [ailgup/Recordify#2] opened 2018-02-19 19:23 UTC
After startup, there is this error:
(spotify was started)

![recordify-error-1](https://user-images.githubusercontent.com/3764279/36394032-9d0fdfda-15b2-11e8-92d2-b8278dd4352b.png)

![recordify-error](https://user-images.githubusercontent.com/3764279/36394011-7efb1b36-15b2-11e8-8f86-b5ac728f38ab.png)

**Comment by ailgup** [comment] 2018-02-20 14:28
Ha didn't think anyone actually used this!
This is a known issue caused by the fact that Spotify has changed their authentication for their API to require an access token. I have a fix working locally and will make a release when I get a chance.

**Comment by ailgup** [comment] 2018-02-23 01:43
Thanks for the reminder, this is now fixed with release V1.5

**Closed as completed by ailgup** 2018-02-23 01:43 UTC

**Comment by vosykapavel** [comment] 2018-02-23 12:09
Thanks for your fast bugfix! It is a great app. I have spotify premium, but I bought a "new" car without aux in, so i need to record some songs and burn them on CD. Thank. I didn't find better apps on the internet. And this is not paid. Nice.
